const allRecipesData = [
  { id: 0, name: 'Brief Answers to the Big Questions', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-1.jpg'},
  { id: 1, name: 'The Grand Design', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-2.jpg'},
  { id: 2, name: 'A Brief History of Time', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-3.jpg'},
  { id: 3, name: 'The Future of Theoretical Physics and Cosmology', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-4a.jpg'},
  { id: 4, name: 'Black Holes: the Reith Lectures', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-5.jpg'},
  { id: 5, name: 'The Theory of Everything', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-6.jpg'},
  { id: 6, name: "Euclid's Window: The Story of Geometry from Parallel Lines", img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-7.jpg'},
  { id: 7, name: "Feynman's Rainbow", img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-8.jpg'},
  { id: 8, name: 'Black Holes and Time Warps', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-9.jpg'},
  { id: 9, name: 'The Science of Interstellar', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-10.jpg'},
  { id: 10, name: 'The Future of Spacetime', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-11.jpg'},
  { id: 11, name: 'Emotional: The New Thinking About Feelings', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-12.jpg'},
  { id: 12, name: "The Drunkard's Walk: How Randomness Rules Our Lives", img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-13.jpg'},
  { id: 13, name: 'The Upright Thinkers: The Human Journey from Living in Trees...', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-14.jpg'},
  { id: 14, name: 'Elastic: Flexibe Thinking in a Constantly Changing World', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-15.jpg'},
  { id: 15, name: 'Gravitation', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-16.jpg'},
  { id: 16, name: 'The Whole Shebang: A state of the Universe Report', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-17.jpg'},
  { id: 17, name: 'Einstein Was Right', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-18.jpg'},
  { id: 18, name: 'Black Holes: The Membrane Paradigm', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-19.jpg'},
  { id: 19, name: "Carl Sagan's Cosmic Connection: An Extraterrestrial Perspective", img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-20.jpg'},
  { id: 20, name: 'Cosmos', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-21.jpg'},
  { id: 21, name: 'Billions & Billions: Thoughts on Life and Death at the Brink', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-22.jpg'},
  { id: 22, name: "Broca's Brain: Reflections on the Romance of Science", img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-23.jpg'},
  { id: 23, name: 'The Dragons of Eden: Speculations on the Evolution of Human Intelligence', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-24.jpg'},
  { id: 24, name: 'Pale Blue Dot: A Vision of the Human Future in Space', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-25.jpg'},
  { id: 25, name: 'The Selfish Gene', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-26.jpg'},
  { id: 26, name: 'An Appetite for Wonder: The Making of a Scientist', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-27.jpg'},
  { id: 27, name: 'The Greatest Show on Earth: The Evidence for Evolution', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-28.jpg'},
  { id: 28, name: 'The Extended Phenotype: The Long Reach of the Gene', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-29.jpg'},
  { id: 29, name: 'Coming of Age in the Milky Way', img: 'https://raw.githubusercontent.com/ARBUCHELI/BOOK-PROJECT-IMAGES/master/book-30.jpg'},
];

export default allRecipesData;
